const list = [
    {
      id: 1,
      title: "Matrix Antique 2.0 ",
      author: "Visit The Matrix Store",
      price: 329,
      img: "https://m.media-amazon.com/images/I/711NXCmUfbL._SL1500_.jpg",
      amount: 1,
    },
    {
      id: 2,
      title: "Fastrack Limitless Fs2",
      author: "Visit the Fastrack store",
      price: 1999,
      img: "https://m.media-amazon.com/images/I/61MVqhtVBuL._SL1080_.jpg",
      amount: 1,
    },
    {
      id: 3,
      title: "HP Victus Laptop",
      author: "Visit The HP store",
      price: 54990,
      img: "https://m.media-amazon.com/images/I/71VZDqJwIML._SL1500_.jpg",
      amount: 1,
    },
    {
      id: 4,
      title: "Adidas Harquin Sneaker",
      author: "Visit the adidas store",
      price: 2136,
      img: "https://m.media-amazon.com/images/I/61fWZXOEd9L._SL1500_.jpg",
      amount: 1,
    },
    {
      id: 5,
      title: "Razer Orochi V2",
      author: "Visit the Razer store",
      price: 3999,
      img: "https://m.media-amazon.com/images/I/41cjX3w4m1S._SL1000_.jpg",
      amount: 1,
    },
    {
      id: 6,
      title: "OnePlus Nord Buds 2",
      author: "Visit the OnePlus Store",
      price: 2999,
      img: "https://m.media-amazon.com/images/I/61-ZYvldY+L._SL1500_.jpg",
      amount: 1,
    },
    {
      id: 7,
      title: "ASUS Vivobook Go 15",
      author: "Visit the ASUS store",
      price: 56490,
      img: "https://m.media-amazon.com/images/I/71nAEVpqXuL._SL1500_.jpg",
      amount: 1,
    },
    {
      id: 8,
      title: "HUION HS64 ",
      author: "Visit the HUION store",
      price: 2600,
      img: "https://m.media-amazon.com/images/I/51dAV1h36zL._SL1500_.jpg",
      amount: 1,
    },
    {
      id: 9,
      title: "boAt Airdopes 121",
      author: "Visit the boAt store",
      price: 899,
      img: "https://m.media-amazon.com/images/I/71NUjpQoUzL._SL1500_.jpg",
      amount: 1,
    },
    
];

export default list;